require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AltarBoysController do

  # This should return the minimal set of attributes required to create a valid
  # AltarBoy. As you add validations to AltarBoy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AltarBoysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all altar_boys as @altar_boys" do
      altar_boy = AltarBoy.create! valid_attributes
      get :index, {}, valid_session
      assigns(:altar_boys).should eq([altar_boy])
    end
  end

  describe "GET show" do
    it "assigns the requested altar_boy as @altar_boy" do
      altar_boy = AltarBoy.create! valid_attributes
      get :show, {:id => altar_boy.to_param}, valid_session
      assigns(:altar_boy).should eq(altar_boy)
    end
  end

  describe "GET new" do
    it "assigns a new altar_boy as @altar_boy" do
      get :new, {}, valid_session
      assigns(:altar_boy).should be_a_new(AltarBoy)
    end
  end

  describe "GET edit" do
    it "assigns the requested altar_boy as @altar_boy" do
      altar_boy = AltarBoy.create! valid_attributes
      get :edit, {:id => altar_boy.to_param}, valid_session
      assigns(:altar_boy).should eq(altar_boy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AltarBoy" do
        expect {
          post :create, {:altar_boy => valid_attributes}, valid_session
        }.to change(AltarBoy, :count).by(1)
      end

      it "assigns a newly created altar_boy as @altar_boy" do
        post :create, {:altar_boy => valid_attributes}, valid_session
        assigns(:altar_boy).should be_a(AltarBoy)
        assigns(:altar_boy).should be_persisted
      end

      it "redirects to the created altar_boy" do
        post :create, {:altar_boy => valid_attributes}, valid_session
        response.should redirect_to(AltarBoy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved altar_boy as @altar_boy" do
        # Trigger the behavior that occurs when invalid params are submitted
        AltarBoy.any_instance.stub(:save).and_return(false)
        post :create, {:altar_boy => { "name" => "invalid value" }}, valid_session
        assigns(:altar_boy).should be_a_new(AltarBoy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AltarBoy.any_instance.stub(:save).and_return(false)
        post :create, {:altar_boy => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested altar_boy" do
        altar_boy = AltarBoy.create! valid_attributes
        # Assuming there are no other altar_boys in the database, this
        # specifies that the AltarBoy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AltarBoy.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => altar_boy.to_param, :altar_boy => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested altar_boy as @altar_boy" do
        altar_boy = AltarBoy.create! valid_attributes
        put :update, {:id => altar_boy.to_param, :altar_boy => valid_attributes}, valid_session
        assigns(:altar_boy).should eq(altar_boy)
      end

      it "redirects to the altar_boy" do
        altar_boy = AltarBoy.create! valid_attributes
        put :update, {:id => altar_boy.to_param, :altar_boy => valid_attributes}, valid_session
        response.should redirect_to(altar_boy)
      end
    end

    describe "with invalid params" do
      it "assigns the altar_boy as @altar_boy" do
        altar_boy = AltarBoy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AltarBoy.any_instance.stub(:save).and_return(false)
        put :update, {:id => altar_boy.to_param, :altar_boy => { "name" => "invalid value" }}, valid_session
        assigns(:altar_boy).should eq(altar_boy)
      end

      it "re-renders the 'edit' template" do
        altar_boy = AltarBoy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AltarBoy.any_instance.stub(:save).and_return(false)
        put :update, {:id => altar_boy.to_param, :altar_boy => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested altar_boy" do
      altar_boy = AltarBoy.create! valid_attributes
      expect {
        delete :destroy, {:id => altar_boy.to_param}, valid_session
      }.to change(AltarBoy, :count).by(-1)
    end

    it "redirects to the altar_boys list" do
      altar_boy = AltarBoy.create! valid_attributes
      delete :destroy, {:id => altar_boy.to_param}, valid_session
      response.should redirect_to(altar_boys_url)
    end
  end

end
