require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ServiceDailySchemasController do

  # This should return the minimal set of attributes required to create a valid
  # ServiceDailySchema. As you add validations to ServiceDailySchema, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "celebration_daily_schema" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ServiceDailySchemasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all service_daily_schemas as @service_daily_schemas" do
      service_daily_schema = ServiceDailySchema.create! valid_attributes
      get :index, {}, valid_session
      assigns(:service_daily_schemas).should eq([service_daily_schema])
    end
  end

  describe "GET show" do
    it "assigns the requested service_daily_schema as @service_daily_schema" do
      service_daily_schema = ServiceDailySchema.create! valid_attributes
      get :show, {:id => service_daily_schema.to_param}, valid_session
      assigns(:service_daily_schema).should eq(service_daily_schema)
    end
  end

  describe "GET new" do
    it "assigns a new service_daily_schema as @service_daily_schema" do
      get :new, {}, valid_session
      assigns(:service_daily_schema).should be_a_new(ServiceDailySchema)
    end
  end

  describe "GET edit" do
    it "assigns the requested service_daily_schema as @service_daily_schema" do
      service_daily_schema = ServiceDailySchema.create! valid_attributes
      get :edit, {:id => service_daily_schema.to_param}, valid_session
      assigns(:service_daily_schema).should eq(service_daily_schema)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ServiceDailySchema" do
        expect {
          post :create, {:service_daily_schema => valid_attributes}, valid_session
        }.to change(ServiceDailySchema, :count).by(1)
      end

      it "assigns a newly created service_daily_schema as @service_daily_schema" do
        post :create, {:service_daily_schema => valid_attributes}, valid_session
        assigns(:service_daily_schema).should be_a(ServiceDailySchema)
        assigns(:service_daily_schema).should be_persisted
      end

      it "redirects to the created service_daily_schema" do
        post :create, {:service_daily_schema => valid_attributes}, valid_session
        response.should redirect_to(ServiceDailySchema.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved service_daily_schema as @service_daily_schema" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceDailySchema.any_instance.stub(:save).and_return(false)
        post :create, {:service_daily_schema => { "celebration_daily_schema" => "invalid value" }}, valid_session
        assigns(:service_daily_schema).should be_a_new(ServiceDailySchema)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceDailySchema.any_instance.stub(:save).and_return(false)
        post :create, {:service_daily_schema => { "celebration_daily_schema" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested service_daily_schema" do
        service_daily_schema = ServiceDailySchema.create! valid_attributes
        # Assuming there are no other service_daily_schemas in the database, this
        # specifies that the ServiceDailySchema created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ServiceDailySchema.any_instance.should_receive(:update).with({ "celebration_daily_schema" => "" })
        put :update, {:id => service_daily_schema.to_param, :service_daily_schema => { "celebration_daily_schema" => "" }}, valid_session
      end

      it "assigns the requested service_daily_schema as @service_daily_schema" do
        service_daily_schema = ServiceDailySchema.create! valid_attributes
        put :update, {:id => service_daily_schema.to_param, :service_daily_schema => valid_attributes}, valid_session
        assigns(:service_daily_schema).should eq(service_daily_schema)
      end

      it "redirects to the service_daily_schema" do
        service_daily_schema = ServiceDailySchema.create! valid_attributes
        put :update, {:id => service_daily_schema.to_param, :service_daily_schema => valid_attributes}, valid_session
        response.should redirect_to(service_daily_schema)
      end
    end

    describe "with invalid params" do
      it "assigns the service_daily_schema as @service_daily_schema" do
        service_daily_schema = ServiceDailySchema.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceDailySchema.any_instance.stub(:save).and_return(false)
        put :update, {:id => service_daily_schema.to_param, :service_daily_schema => { "celebration_daily_schema" => "invalid value" }}, valid_session
        assigns(:service_daily_schema).should eq(service_daily_schema)
      end

      it "re-renders the 'edit' template" do
        service_daily_schema = ServiceDailySchema.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceDailySchema.any_instance.stub(:save).and_return(false)
        put :update, {:id => service_daily_schema.to_param, :service_daily_schema => { "celebration_daily_schema" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested service_daily_schema" do
      service_daily_schema = ServiceDailySchema.create! valid_attributes
      expect {
        delete :destroy, {:id => service_daily_schema.to_param}, valid_session
      }.to change(ServiceDailySchema, :count).by(-1)
    end

    it "redirects to the service_daily_schemas list" do
      service_daily_schema = ServiceDailySchema.create! valid_attributes
      delete :destroy, {:id => service_daily_schema.to_param}, valid_session
      response.should redirect_to(service_daily_schemas_url)
    end
  end

end
