require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ServiceTypesTarrifsController do

  # This should return the minimal set of attributes required to create a valid
  # ServiceTypesTarrif. As you add validations to ServiceTypesTarrif, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "service_type" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ServiceTypesTarrifsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all service_types_tarrifs as @service_types_tarrifs" do
      service_types_tarrif = ServiceTypesTarrif.create! valid_attributes
      get :index, {}, valid_session
      assigns(:service_types_tarrifs).should eq([service_types_tarrif])
    end
  end

  describe "GET show" do
    it "assigns the requested service_types_tarrif as @service_types_tarrif" do
      service_types_tarrif = ServiceTypesTarrif.create! valid_attributes
      get :show, {:id => service_types_tarrif.to_param}, valid_session
      assigns(:service_types_tarrif).should eq(service_types_tarrif)
    end
  end

  describe "GET new" do
    it "assigns a new service_types_tarrif as @service_types_tarrif" do
      get :new, {}, valid_session
      assigns(:service_types_tarrif).should be_a_new(ServiceTypesTarrif)
    end
  end

  describe "GET edit" do
    it "assigns the requested service_types_tarrif as @service_types_tarrif" do
      service_types_tarrif = ServiceTypesTarrif.create! valid_attributes
      get :edit, {:id => service_types_tarrif.to_param}, valid_session
      assigns(:service_types_tarrif).should eq(service_types_tarrif)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ServiceTypesTarrif" do
        expect {
          post :create, {:service_types_tarrif => valid_attributes}, valid_session
        }.to change(ServiceTypesTarrif, :count).by(1)
      end

      it "assigns a newly created service_types_tarrif as @service_types_tarrif" do
        post :create, {:service_types_tarrif => valid_attributes}, valid_session
        assigns(:service_types_tarrif).should be_a(ServiceTypesTarrif)
        assigns(:service_types_tarrif).should be_persisted
      end

      it "redirects to the created service_types_tarrif" do
        post :create, {:service_types_tarrif => valid_attributes}, valid_session
        response.should redirect_to(ServiceTypesTarrif.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved service_types_tarrif as @service_types_tarrif" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceTypesTarrif.any_instance.stub(:save).and_return(false)
        post :create, {:service_types_tarrif => { "service_type" => "invalid value" }}, valid_session
        assigns(:service_types_tarrif).should be_a_new(ServiceTypesTarrif)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceTypesTarrif.any_instance.stub(:save).and_return(false)
        post :create, {:service_types_tarrif => { "service_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested service_types_tarrif" do
        service_types_tarrif = ServiceTypesTarrif.create! valid_attributes
        # Assuming there are no other service_types_tarrifs in the database, this
        # specifies that the ServiceTypesTarrif created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ServiceTypesTarrif.any_instance.should_receive(:update).with({ "service_type" => "" })
        put :update, {:id => service_types_tarrif.to_param, :service_types_tarrif => { "service_type" => "" }}, valid_session
      end

      it "assigns the requested service_types_tarrif as @service_types_tarrif" do
        service_types_tarrif = ServiceTypesTarrif.create! valid_attributes
        put :update, {:id => service_types_tarrif.to_param, :service_types_tarrif => valid_attributes}, valid_session
        assigns(:service_types_tarrif).should eq(service_types_tarrif)
      end

      it "redirects to the service_types_tarrif" do
        service_types_tarrif = ServiceTypesTarrif.create! valid_attributes
        put :update, {:id => service_types_tarrif.to_param, :service_types_tarrif => valid_attributes}, valid_session
        response.should redirect_to(service_types_tarrif)
      end
    end

    describe "with invalid params" do
      it "assigns the service_types_tarrif as @service_types_tarrif" do
        service_types_tarrif = ServiceTypesTarrif.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceTypesTarrif.any_instance.stub(:save).and_return(false)
        put :update, {:id => service_types_tarrif.to_param, :service_types_tarrif => { "service_type" => "invalid value" }}, valid_session
        assigns(:service_types_tarrif).should eq(service_types_tarrif)
      end

      it "re-renders the 'edit' template" do
        service_types_tarrif = ServiceTypesTarrif.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceTypesTarrif.any_instance.stub(:save).and_return(false)
        put :update, {:id => service_types_tarrif.to_param, :service_types_tarrif => { "service_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested service_types_tarrif" do
      service_types_tarrif = ServiceTypesTarrif.create! valid_attributes
      expect {
        delete :destroy, {:id => service_types_tarrif.to_param}, valid_session
      }.to change(ServiceTypesTarrif, :count).by(-1)
    end

    it "redirects to the service_types_tarrifs list" do
      service_types_tarrif = ServiceTypesTarrif.create! valid_attributes
      delete :destroy, {:id => service_types_tarrif.to_param}, valid_session
      response.should redirect_to(service_types_tarrifs_url)
    end
  end

end
